# Getting into SQL with duckdb

## Why DuckDB

There are many database management systems (DBMS) out there. But there is [no one-size-fits all database system](https://blobs.duckdb.org/papers/stonebraker-centintemel-one-size-fits-all-icde-2015.pdf). All take different trade-offs to better adjust to specific use cases. DuckDB is no different. Here, we try to explain what goals DuckDB has and why and how we try to achieve those goals through technical means. To start with, DuckDB is a [relational (table-oriented) DBMS](https://en.wikipedia.org/wiki/Relational_database) that supports the [Structured Query Language (SQL)](https://en.wikipedia.org/wiki/SQL).

## Writing SQL in Jupyter notebooks

DuckDBâ€™s Python client can be used directly in Jupyter notebooks with no additional configuration if desired. However, additional libraries can be used to simplify SQL query development. This guide will describe how to utilize those additional libraries. See other guides in the Python section for how to use DuckDB and Python together.

In this example, we use the [JupySQL](https://github.com/ploomber/jupysql) package.

In [1]:
import duckdb
import pandas as pd

# import jupysql Jupyter extension to create SQL cells
%load_ext sql

# Set configurations on jupysql to directly output data to Pandas
# and to simplify the output that is printed to the notebook.
%config SqlMagic.autopandas = True
%config SqlMagic.feedback = False
%config SqlMagic.displaycon = False

## Working with JupySQL

Connect to the database. We use `presidents.db` for our exercises.

In [2]:
%sql duckdb:///presidents-v0.10.0.duckdb

You can write queries like this:

In [8]:
%sql SELECT * FROM president

,id,name,birth_year,years_served,death_age,party,state_id_born
0,1,WASHINGTON G,1732,7,67.0,FEDERALIST,35
1,2,ADAMS J,1735,4,90.0,FEDERALIST,38
2,3,JEFFERSON T,1743,8,83.0,DEMO-REP,35
3,4,MADISON J,1751,8,85.0,DEMO-REP,35
4,5,MONROE J,1758,8,73.0,DEMO-REP,35
5,6,ADAMS J Q,1767,4,80.0,DEMO-REP,38
6,7,JACKSON A,1767,8,78.0,DEMOCRATIC,40
7,8,VAN BUREN M,1782,4,79.0,DEMOCRATIC,46
8,9,HARRISON W H,1773,0,68.0,WHIG,35
9,10,TYLER J,1790,3,71.0,WHIG,35
10,11,POLK J K,1795,4,53.0,DEMOCRATIC,47
11,12,TAYLOR Z,1784,1,65.0,WHIG,35
12,13,FILLMORE M,1800,2,74.0,WHIG,46
13,14,PIERCE F,1804,4,64.0,DEMOCRATIC,44
14,15,BUCHANAN J,1791,4,77.0,DEMOCRATIC,37
15,16,LINCOLN A,1809,4,56.0,REPUBLICAN,49
16,17,JOHNSON A,1808,3,66.0,DEMOCRATIC,37
17,18,GRANT U S,1822,8,63.0,REPUBLICAN,1
18,19,HAYES R B,1822,4,70.0,REPUBLICAN,1
19,20,GARFIELD J A,1831,0,49.0,REPUBLICAN,1
20,21,ARTHUR C A,1830,3,56.0,REPUBLICAN,36
21,22,CLEVELAND G,1837,8,71.0,DEMOCRATIC,42
22,23,HARRISON B,1833,4,67.0,REPUBLICAN,1
23,24,MCKINLEY W,1843,4,58.0,REPUBLICAN,1
24,25,ROOSEVELT T,1858,7,60.0,REPUBLICAN,46
25,26,TAFT W H,1857,4,72.0,REPUBLICAN,1
26,27,WILSON W,1856,8,67.0,DEMOCRATIC,35
27,28,HARDING W G,1865,2,57.0,REPUBLICAN,1
28,29,COOLIDGE C,1872,5,60.0,REPUBLICAN,36
29,30,HOOVER H C,1874,4,90.0,REPUBLICAN,13
30,31,ROOSEVELT F D,1882,12,63.0,DEMOCRATIC,46
31,32,TRUMAN H S,1884,7,88.0,DEMOCRATIC,8
32,33,EISENHOWER D D,1890,8,79.0,REPUBLICAN,12
33,34,KENNEDY J F,1917,2,46.0,DEMOCRATIC,38
34,35,JOHNSON L B,1908,5,65.0,DEMOCRATIC,12
35,36,NIXON R M,1913,5,81.0,REPUBLICAN,15
36,37,FORD G R,1913,2,93.0,REPUBLICAN,21
37,38,CARTER J M,1924,4,NaN,DEMOCRATIC,43
38,39,BUSH G H W,1924,4,94.0,REPUBLICAN,38
39,40,REAGAN R,1911,8,93.0,REPUBLICAN,5
40,41,CLINTON W J,1946,8,NaN,DEMOCRATIC,9
41,42,BUSH G W,1946,8,NaN,REPUBLICAN,39
42,43,OBAMA B,1961,8,NaN,DEMOCRATIC,34
43,44,TRUMP D J,1946,4,NaN,REPUBLICAN,46
44,45,BIDEN J R,1942,2,NaN,DEMOCRATIC,37

You need to use `%%sql` if you want to write multi-line SQL

In [11]:
%%sql
SELECT *
FROM president
LIMIT 10

,id,name,birth_year,years_served,death_age,party,state_id_born
0,1,WASHINGTON G,1732,7,67,FEDERALIST,35
1,2,ADAMS J,1735,4,90,FEDERALIST,38
2,3,JEFFERSON T,1743,8,83,DEMO-REP,35
3,4,MADISON J,1751,8,85,DEMO-REP,35
4,5,MONROE J,1758,8,73,DEMO-REP,35
5,6,ADAMS J Q,1767,4,80,DEMO-REP,38
6,7,JACKSON A,1767,8,78,DEMOCRATIC,40
7,8,VAN BUREN M,1782,4,79,DEMOCRATIC,46
8,9,HARRISON W H,1773,0,68,WHIG,35
9,10,TYLER J,1790,3,71,WHIG,35

It's your turn now to practice SQL with the exercises!

In [ ]:
%%sql